import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Heritage Modernism Design System
        "error-container": "#ffdad6",
        "surface-container-low": "#f6f3f2",
        "primary-fixed": "#ffdad6",
        "outline-variant": "#e1bfbb",
        "tertiary-fixed-dim": "#94d2ce",
        "inverse-primary": "#ffb4ac",
        "secondary-fixed": "#ffdea5",
        error: "#ba1a1a",
        tertiary: "#003534",
        "on-error-container": "#93000a",
        background: "#fcf9f8",
        "on-primary-fixed": "#410003",
        "inverse-surface": "#313030",
        "on-error": "#ffffff",
        "surface-container-highest": "#e5e2e1",
        "on-background": "#1c1b1b",
        "on-tertiary-fixed-variant": "#054f4d",
        "on-primary-fixed-variant": "#8e1316",
        "tertiary-container": "#024e4c",
        "inverse-on-surface": "#f3f0ef",
        "primary-container": "#8b1014",
        surface: "#fcf9f8",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#e9c176",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-bright": "#fcf9f8",
        "surface-variant": "#e5e2e1",
        "primary-fixed-dim": "#ffb4ac",
        "on-surface-variant": "#59413e",
        "on-surface": "#1c1b1b",
        "on-secondary-fixed-variant": "#5d4201",
        "on-secondary-container": "#785a1a",
        "secondary-container": "#fed488",
        secondary: "#775a19",
        "surface-tint": "#b02d2a",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#dcd9d9",
        "tertiary-fixed": "#b0eeea",
        "on-primary-container": "#ff958c",
        "on-tertiary-container": "#81bebb",
        primary: "#650007",
        outline: "#8d706d",
        "on-tertiary-fixed": "#00201f",
        "surface-container-high": "#eae7e7",
        "surface-container": "#f0eded",
        "on-secondary-fixed": "#261900",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "stack-sm": "8px",
        "stack-lg": "48px",
        "stack-md": "24px",
        gutter: "16px",
        "section-padding": "64px",
        unit: "4px",
        "container-margin": "20px",
      },
      fontFamily: {
        "headline-lg": ["Epilogue", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "headline-xl": ["Epilogue", "sans-serif"],
        "headline-md": ["Epilogue", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "label-sm": ["Manrope", "sans-serif"],
        epilogue: ["Epilogue", "sans-serif"],
        manrope: ["Manrope", "sans-serif"],
      },
      fontSize: {
        "headline-lg": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-xl": [
          "40px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": [
          "12px",
          { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" },
        ],
      },
      boxShadow: {
        whisper:
          "0 30px 60px -12px rgba(101, 0, 7, 0.06)",
        "whisper-md": "0 20px 50px -12px rgba(101, 0, 7, 0.06)",
      },
      maxWidth: {
        "8xl": "1440px",
      },
    },
  },
  plugins: [],
};

export default config;
